### ISSUE TITLE
Controller service name is hardcoded

### ISSUE THREAD

**Issue by rmb938** [Stono/kconmon#7]
https://github.com/Stono/kconmon/blob/master/lib/discovery/service.ts#L21

It would be nice if this could be set  in the agent's config

**Comment by Stono** [comment]
Hey @rmb938,
The controller service _is_ called controller though?   Can you help me understand what circumstance it wouldn't be called controller?

**Comment by rmb938** [comment]
I am deploying this in an environment that has a lot of other services and things running. Having something being named just `controller` isn't descriptive enough for  my environments.

I've tried to deploy it with a more descriptive name like `kconmon-controller` but because it's hardcoded changing the service name can't be done.

**Comment by Stono** [comment]
@rmb938 but it is `controller.namespace`, where the namespace can be unique, thereby your service becomes `controller.whatever-you-want.svc.cluster.local`?

Are you deploying it into an existing namespace (i would advise against that for isolation reasons)?

**Comment by rmb938** [comment]
Yes I am deploying it into existing namespaces.

Namespaces don't isolate anything in Kubernetes, they just provide nice groupings and rbac. All the isolation happens via the containers, network policies, ect...

**Comment by Stono** [comment]
I'm well aware of how kubernetes works 🤣  

By deploying this into the same namespace as other services, you'll be giving the controller permission to `get` all pods within that namespace (see https://github.com/Stono/kconmon/blob/master/helmfile/charts/kconmon/templates/controller/role.yaml) which is more privilege than it requires (it only needs to be able to `get` the agents).

I would strongly suggest putting it in another namespace rather than over granting access to the controller.  If you still wish to put it in the same namespace, I welcome a PR but please make the risk abundantly clear in the README.

**Comment by rmb938** [comment]
Yes I am well aware. For my clusters, and many production ones that major companies  run, that risk is very low, I run tons of operators and other monitoring tools that need get to things like pods, deployments, ect.. at a cluster level. While there is a risk as long as everything is scoped correctly and audited it's not a big deal.

I'll get a PR made though and include that risk warning.

**Comment by Stono** [comment]
Just because many big companies do it, does not make it right.

Just because some services have cluster scope to get all pods, that’s because they need it to function (for example, Prometheus), and again does not make it right.

Neither of these things justify over scoping RBAC when there are less privileged ways to deploy the service. 

Thanks for your thoughts on the matter however upon reflection, I won’t be accepting a PR for this as it goes against the principle of least privilege which is something I feel quite strongly about. 

By all means though fork the helm chart and adjust it for your needs, it’s relatively simple.
