### ISSUE TITLE
Histogram metrics for UDP & TCP duration

### ISSUE THREAD

**Issue by rmb938** [Stono/kconmon#8]
It would be useful to have a histogram metric of the udp & tcp duration https://prometheus.io/docs/concepts/metric_types/#histogram

This way we could graph these metrics by p50, p90, p99, ect..

**Comment by Stono** [comment]
Yes I considered this but the problem is the massive amount to cardinality of those metrics, say 20 le buckets and 100 nodes and 3x test types and you’ve got 6000 extra metrics per pod to scrape, increasing both the memory footprint and network io. 

Therefore I was satisfied with the average because from that you can make inferences from the trend to visualise issues.  I appreciate it makes spotting outliers harder however, which is why I also record variance between min and max on the UDP test. 

If you wish to add it however feel free to send a PR but I would ask for it to be behind a feature flag that defaults off so people can opt in knowing the overhead.

**Comment by rmb938** [comment]
Ah yea that is true. I was thinking it would replace the current duration metrics but histograms do end up with more timeseries in general.

So your reasoning for not having them does makes sense.
